account/urls.py
from django.urls import path

from . import views

app_name = 'account'

urlpatterns = [
    path('dashboard/', views.DashboardView.as_view(), name='dashboard'),
    path('create_shipment/', views.create_new_shipment, name='create_shipment'),
    path('edit_shipment/<pk>/', views.edit_shipment, name='edit_shipment'),
    path('shipment_details/<pk>/', views.shipment_detail, name='shipment_detail'),
    path('delete_shipment/<pk>/', views.delete_shipment, name='delete_shipment'),

    path('update_live_update/<pk>/', views.update_live_update, name='update_live_update'),
    path('delete_live_update/<pk>/', views.delete_live_update, name='delete_live_update'),
    path('view_receipt/<pk>/', views.view_receipt, name='view_receipt'),

    # twilio
    path('send-sms/<pk>/', views.admin_send_sms, name='admin_send_sms'),
    path('sms/status_callback/', views.sms_status_callback, name='sms_status_callback'),
]

frontend/urls.py
from django.urls import path

from . import views

app_name = 'frontend'

urlpatterns = [
    path('', views.home, name="home"),
    path('track-shipment/', views.track_shipment, name="track_shipment"),
    path('login/', views.loginUser, name='login'),
    path('logout/', views.logoutUser, name='logout'),
    path('about_us/', views.about_us, name='about_us'),
    path('service/', views.service, name='service'),
    path('contact_us/', views.contact_us, name='contact_us'),
]

unviversalfx/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('account/', include('account.urls', namespace='account')),
    path('', include('frontend.urls', namespace='frontend')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

frontend/models.py
from django.db import models

# Create your models here.

frontend/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.template.loader import render_to_string
import json

from account.models import Shipment, LiveUpdate
from . import emailsend


def loginUser(request):
    if request.method == "POST":
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('account:dashboard')    
        else:
            messages.info(request, 'Username or Password is incorrect')
    return render(request, 'frontend/login.html')


def home(request):
    return render(request, 'frontend/index.html')


def track_shipment(request):
    tracking_code = request.GET.get('tracking_number') or request.POST.get('tracking_code')

    if tracking_code:
        shipments = Shipment.objects.filter(tracking_number=tracking_code)

        if shipments.exists():
            shipment_single = shipments.first()
            live_update = LiveUpdate.objects.filter(shipment=shipment_single)
            live_update_count = live_update.count()
            latest_update = live_update.last()

            # Prepare list of locations with lat/lon for JS
            locations = [
                {
                    "lat": update.latitude,
                    "lng": update.longitude,
                    "location": update.current_location,
                    "status": update.status,
                    "time": update.created_on.strftime("%Y-%m-%d %H:%M:%S")
                }
                for update in live_update if update.latitude is not None and update.longitude is not None
            ]

            return render(request, 'frontend/track_shipment.html', {
                'shipments': shipments,
                'shipment_single': shipment_single,
                'update_count': live_update_count,
                'latest_update': latest_update,
                'live_update': live_update,
                'auto_tracked': True,  # Optional flag for your template
                'locations_json': json.dumps(locations),
            })
        else:
            messages.error(request, "Invalid tracking code. Please check the code and try again.")
            return redirect('frontend:track_shipment')

    return render(request, 'frontend/track_shipment.html')



@login_required()
def logoutUser(request):
	logout(request)
	return redirect('frontend:login')


def about_us(request):
    return render(request, 'frontend/about_us.html')

def service(request):
    return render(request, 'frontend/service.html')


def contact_us(request):

    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        subject = request.POST.get('subject')
        message = request.POST.get('message')

        final_message = render_to_string('frontend/emails/customer_care_email.html', 
        {
            'name': name,
            'email': email,
            'message': message,
            'subject': subject
        })

        try:
            emailsend.email_send(
                'Email From '+name,
                final_message,
                'contact@metroworldexpress.com',
            )
            messages.success(request, 'Email sent successfully, we will get back to you as soon as possible')
        except:
            messages.error(request, 'There was an error while trying to send your email, please try again')

        finally:
            return redirect('frontend:contact_us')
    return render(request, 'frontend/contact.html')

templates/frontend/includes/footer.html
{% load static %}
<!-- Footer Start -->
<div class="container-fluid bg-dark text-light footer pt-5 wow fadeIn" data-wow-delay="0.1s" style="margin-top: 6rem;">
    <div class="container py-5">
        <div class="row g-5">
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Address</h4>
                <p class="mb-2"><i class="fa fa-map-marker-alt me-3"></i>1619 State Street, Detroit, MI</p>
                <!-- <p class="mb-2"><i class="fa fa-phone-alt me-3"></i>+012 345 67890</p> -->
                <p class="mb-2" style="font-size: 12px;"><i class="fa fa-envelope me-3"></i>contact@metroworldexpress.com</p>
                <!-- <div class="d-flex pt-2">
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-twitter"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-facebook-f"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-youtube"></i></a>
                    <a class="btn btn-outline-light btn-social" href=""><i class="fab fa-linkedin-in"></i></a>
                </div> -->
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Services</h4>
                <a class="btn btn-link" href="/">Air Freight</a>
                <a class="btn btn-link" href="/">Sea Freight</a>
                <a class="btn btn-link" href="/">Road Freight</a>
                <a class="btn btn-link" href="/">Logistic Solutions</a>
                <a class="btn btn-link" href="/">Industry solutions</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Quick Links</h4>
                <a class="btn btn-link" href="{% url 'frontend:about_us' %}">About Us</a>
                <a class="btn btn-link" href="{% url 'frontend:contact_us' %}">Contact Us</a>
                <a class="btn btn-link" href="{% url 'frontend:service' %}">Our Services</a>
                <a class="btn btn-link" href="/">Terms &amp; Condition</a>
                <a class="btn btn-link" href="/">Support</a>
            </div>
            <div class="col-lg-3 col-md-6">
                <h4 class="text-light mb-4">Newsletter</h4>
                <p>Subscribe to get our latest news for update and offer.</p>
                <div class="position-relative mx-auto" style="max-width: 400px;">
                    <input class="form-control border-0 w-100 py-3 ps-4 pe-5" type="text" placeholder="Your email">
                    <button type="button" class="btn btn-primary py-2 position-absolute top-0 end-0 mt-2 me-2">SignUp</button>
                </div>
            </div>
        </div>
    </div>
    <div class="container">
        <div class="copyright">
            <div class="row">
                <div class="col-md-6 text-center text-md-start mb-3 mb-md-0">
                    © <a class="border-bottom" href="#">Metro World eXpress</a>, All Right Reserved.
                </div>
                <!-- <div class="col-md-6 text-center text-md-end">
                    Designed By <a class="border-bottom" href="">HTML Codex</a>
                    <br>Distributed By <a class="border-bottom" href="https://themewagon.com" target="_blank">ThemeWagon</a>
                </div> -->
            </div>
        </div>
    </div>
</div>
<!-- Footer End -->

templates/frontend/includes/navbar.html
<!-- Navbar Start -->
<nav class="navbar navbar-expand-lg bg-white navbar-light shadow border-top border-5 border-primary sticky-top p-0">
    <a href="/" class="navbar-brand bg-primary d-flex align-items-center px-4 px-lg-5">
        <h2 class="mb-2 text-white">MetroWorldeXpress</h2>
    </a>
    <button type="button" class="navbar-toggler me-4" data-bs-toggle="collapse" data-bs-target="#navbarCollapse">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <div class="navbar-nav ms-auto p-4 p-lg-0">
            <a href="/" class="nav-item nav-link active">Home</a>
            <a href="{% url 'frontend:about_us' %}" class="nav-item nav-link">About</a>
            <a href="{% url 'frontend:service' %}" class="nav-item nav-link">Services</a>
            <a href="{% url 'frontend:track_shipment' %}" class="nav-item nav-link">Track Shipment</a>
            <a href="{% url 'frontend:contact_us' %}" class="nav-item nav-link">Contact Us</a>
        </div>
        <!-- <h4 class="m-0 pe-lg-5 d-none d-lg-block"><i class="fa fa-headphones text-primary me-3"></i>+012 345 6789</h4> -->
        <div id="google_translate_element" class="mt-2 ms-3"></div>
    </div>
</nav>
<!-- Navbar End -->